// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./csv_uploads_controller"
import Csv_uploads_controller from "./csv_uploads_controller";
application.register("csv-uploads", Csv_uploads_controller)
